// Generated by scripts/export-protocol-types.py; do not edit by hand.

export interface FlyProfile {
  id: string;
  name: string;
  style: string;
  accent: string;
  chips: number;
  seat: number;
  alive: boolean;
  hole_cards: Array<string>;
  equity: number;
  activity: number;
  vpip: number;
  pfr: number;
  aggression: number;
  tell: string;
  status: string;
}

export interface TableSnapshot {
  mode: "simulated" | "flybrain";
  tournament_id: string;
  hand_id: string;
  deck_seed: number;
  hand_number: number;
  street: string;
  board: Array<string>;
  pot: number;
  current_actor: string | null;
  blind_level: number;
  blinds: string;
  players: Array<FlyProfile>;
  last_event: string;
  sequence: number;
  updated_at: string;
}

export interface EventEnvelope {
  schemaVersion: number;
  tournamentId: string;
  handId: string;
  sequence: number;
  serverTime: string;
  type: string;
  payload: EventPayload;
}

export interface EventPayload {
  status?: string;
  mode?: "simulated" | "flybrain";
  reason?: string;
  message?: string;
  tournamentId?: string;
  handNumber?: number;
  blinds?: string;
  deckSeed?: number;
  players?: Array<unknown>;
  playerId?: string;
  street?: string;
  board?: Array<string>;
  action?: string;
  amount?: number;
  sizing?: string;
  pot?: number;
  stacks?: Array<number>;
  logits?: Record<string, number>;
  features?: Record<string, number>;
  legalActions?: Array<string>;
  winnerId?: string;
  winnerIds?: Array<string>;
  payouts?: Record<string, number>;
  payoffs?: Array<number>;
  replaySlug?: string;
  slug?: string;
  seeds?: Array<number>;
  activity?: number;
  regions?: Record<string, number>;
  sampledSpikes?: Array<number>;
  sampledNeuronCount?: number;
  stimulatedPopulations?: Array<string>;
  [key: string]: unknown;
}

export interface SnapshotMessage {
  kind: "snapshot";
  snapshot: TableSnapshot;
  sequence: number;
}

export interface EventMessage {
  kind: "event";
  event: EventEnvelope;
}

export interface StatusResponse {
  status: "live" | "starting" | "offline";
  mode: "simulated" | "flybrain";
  gpu: string;
  connected_spectators: number;
  step_latency_ms: number;
  current_hand: number;
  brain_runtime: "simulated" | "available" | "unavailable";
  runtime_note: string;
  updated_at: string;
}
