"""Generate TypeScript protocol interfaces from the Pydantic JSON schema."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas" / "live-protocol.schema.json"
OUTPUT = ROOT / "lib" / "protocol.generated.ts"


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(option) for option in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional)}>"
        return "Record<string, unknown>"
    return {
        "string": "string",
        "null": "null",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
    }.get(kind, "unknown")


def render_interface(name: str, schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in properties.items():
        # These are response/event interfaces. Pydantic includes defaulted
        # fields in model_dump(), so every declared property is on the wire;
        # nullability is represented by the generated union instead. Event
        # payloads are intentionally partial because each event type carries
        # a different subset of the forward-compatible fields.
        optional = name == "EventPayload" and property_name not in required
        lines.append(f"  {property_name}{'?' if optional else ''}: {ts_type(property_schema)};")
    if schema.get("additionalProperties") is True:
        lines.append("  [key: string]: unknown;")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    definitions = schema["$defs"]
    output = "// Generated by scripts/export-protocol-types.py; do not edit by hand.\n\n"
    output += "\n\n".join(render_interface(name, definition) for name, definition in definitions.items())
    OUTPUT.write_text(output + "\n", encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
